(() => {
  const interactionStyle = document.createElement('style'); interactionStyle.textContent = `.page-story{opacity:0;transform:translateY(28px);transition:opacity .7s ease,transform .7s ease}.page-story.is-visible{opacity:1;transform:none}.page-story figure{cursor:zoom-in;transition:transform .3s ease}.page-story figure:hover{transform:scale(1.012)}.image-lightbox{position:fixed;inset:0;z-index:30;background:#000e;display:grid;place-items:center;padding:28px;opacity:0;pointer-events:none;transition:opacity .25s ease}.image-lightbox.open{opacity:1;pointer-events:auto}.image-lightbox img{max-width:min(1100px,96vw);max-height:88vh;border-radius:12px;box-shadow:0 25px 90px #000}.image-lightbox button{position:absolute;top:22px;right:26px;border:0;border-radius:50%;width:36px;height:36px;background:#303036;color:#fff;font-size:24px;cursor:pointer}`; document.head.appendChild(interactionStyle);
  const extraStyle = document.createElement("style"); extraStyle.textContent = `.hero-facts{display:flex;justify-content:center;gap:10px;flex-wrap:wrap;margin:0 auto 28px;color:#c6c6cc;font-size:13px}.hero-facts span{border:1px solid #3a3a42;background:#17171b;border-radius:999px;padding:7px 11px}.product-overview{padding:110px 0 35px}.product-overview h2,.workflow-section h2,.audience-section h2{font-size:clamp(38px,5vw,62px);letter-spacing:-.065em;line-height:1.04;margin:0 0 20px;max-width:760px}.product-overview>p:not(.eyebrow){max-width:680px;color:var(--muted);font-size:20px;line-height:1.6}.workflow-section{padding:80px 0 110px;background:#101014}.workflow-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.workflow-grid article{background:#1c1c20;border:1px solid #2d2d32;border-radius:15px;padding:20px;min-height:190px}.workflow-grid b{color:var(--blue);font-size:13px}.workflow-grid h3{font-size:20px;margin:36px 0 10px}.workflow-grid p{color:var(--muted);font-size:14px;line-height:1.55;margin:0}.audience-section{padding:105px 0;background:#0b0b0e}.audience-section .wrap{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center}.audience-section ul{list-style:none;padding:0;margin:0;display:grid;gap:10px}.audience-section li{padding:18px 20px;border:1px solid #2d2d32;border-radius:12px;color:#d2d2d7}.audience-section li:before{content:'→';color:var(--blue);margin-right:10px}@media(max-width:720px){.workflow-grid{grid-template-columns:1fr 1fr}.audience-section .wrap{grid-template-columns:1fr;gap:30px}}`; document.head.appendChild(extraStyle);
  const escape = (v) => String(v).replace(/[&<>'"]/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
  const id = new URLSearchParams(location.search).get("product") || "airename";
  const p = (window.INSPIRATION_PRODUCTS || []).find((x) => x.id === id);
  const page = document.querySelector("#product-page");
  if (!p) { page.innerHTML = '<section class="product-page-hero wrap"><h1>没有找到这个产品</h1><a class="button button-primary" href="index.html">返回首页</a></section>'; return; }
  document.title = `${p.name} · lnspiration`;
  const isAirename = p.id === "airename";
  const isPlugin = p.id === "animationpathprotector";
  const heroTitle = isAirename ? "AI Rename" : p.name;
  const audience = isAirename ? ["设计师与视觉团队", "游戏、美术与素材制作团队", "需要整理大量图片资源的个人创作者"] : isPlugin ? ["使用 Animator 驱动角色、道具或 UI 动画的 Unity 项目", "需要频繁调整层级结构的美术与技术美术团队", "希望重构节点命名而不破坏动画的开发者"] : ["经常阅读外文资料的人", "需要跨语言沟通的设计与开发团队", "希望减少窗口切换的效率型用户"];
  const workflow = isAirename ? [{n:"01",t:"导入素材",d:"拖入图片、PSD 或 PSB，建立清晰的资产处理队列。"},{n:"02",t:"设置规则",d:"选择标签、匹配、序列化、增删剪裁或 AI 精准映射。"},{n:"03",t:"检查预览",d:"同时确认名称、格式、画布、背景和覆盖方式。"},{n:"04",t:"批量处理",d:"处理选中项或全部资源，导出副本或安全覆盖原文件。"}] : isPlugin ? [{n:"01",t:"创建 Animator",d:"在角色、道具或 UI 对象上准备 Animator 与动画控制器。"},{n:"02",t:"挂载保护组件",d:"将 Animation Path Protector 挂载到 Animator 对象，建立动画路径快照。"},{n:"03",t:"自由修改层级",d:"随意移动节点、调整层级、修改名称或重构对象结构。"},{n:"04",t:"自动接驳动画",d:"插件识别变化并同步动画曲线路径，让原有动画继续正确工作。"}] : [{n:"01",t:"唤出翻译",d:"按下全局快捷键，不离开当前网页、文档或应用。"},{n:"02",t:"确认语言",d:"选择输入与输出语言，使用适合当前任务的翻译服务。"},{n:"03",t:"阅读结果",d:"在轻量窗口中查看译文，继续保持当前工作节奏。"},{n:"04",t:"安静常驻",d:"关闭窗口后回到托盘，需要时再次呼出。"}];
  const stories = (p.stories || []).map((s, i) => `<article class="page-story ${i % 2 ? "reverse" : ""}"><div class="story-copy"><p class="eyebrow">${escape(p.fullName)}</p><h2>${escape(s.title)}</h2><p>${escape(s.text)}</p></div><figure><img src="${escape(s.image)}" alt="${escape(s.alt)}" loading="lazy"></figure></article>`).join("");
  const features = (p.features || []).map((x) => `<li>${escape(x)}</li>`).join("");
  const audienceHtml = audience.map((x) => `<li>${escape(x)}</li>`).join("");
  const workflowHtml = workflow.map((x) => `<article><b>${x.n}</b><h3>${escape(x.t)}</h3><p>${escape(x.d)}</p></article>`).join("");
  const assets = (p.assets || []).map((a) => `<a class="page-download" href="${escape(a.url)}" download><span><strong>${escape(a.label)}</strong><small>${escape(a.name)}</small></span><b>直接下载 ↓</b></a>`).join("");
  page.innerHTML = `<section class="product-page-hero"><div class="wrap"><p class="eyebrow">${escape(p.fullName)}</p><h1>${escape(heroTitle)}</h1><p>${escape(p.description)}</p><div class="hero-facts"><span>${escape(p.platforms)}</span><span>当前版本 v${escape(p.version)}</span><span>独立桌面工具</span></div><a class="button button-primary" href="${escape(p.assets[0].url)}" download>下载 v${escape(p.version)}</a></div></section><section class="product-overview wrap"><p class="eyebrow">为什么选择 ${escape(p.name)}</p><h2>${isAirename ? "把重复整理，交给更聪明的工作流。" : "让翻译成为工作流的一部分。"}</h2><p>${isAirename ? "从素材导入、命名规则到最终输出，Airename 把复杂的批处理拆成清晰可控的每一步。" : "翻译虎不试图占据你的屏幕，它只在需要的时候出现，让语言转换像快捷键一样自然。"}</p></section><section class="workflow-section"><div class="wrap"><p class="eyebrow">简单四步</p><h2>${isAirename ? "从素材到结果，始终看得见。" : "从唤出到理解，不必离开当前工作。"}</h2><div class="workflow-grid">${workflowHtml}</div></div></section><section class="product-stories wrap">${stories}</section><section class="feature-section"><div class="wrap"><p class="eyebrow">完整能力</p><h2>${isAirename ? "为批量创作而生。" : "为轻快沟通而生。"}</h2><ul>${features}</ul></div></section><section class="audience-section"><div class="wrap"><div><p class="eyebrow">适合谁</p><h2>${isAirename ? "把时间还给创作。" : "让每个人都能快速理解。"}</h2></div><ul>${audienceHtml}</ul></div></section><section class="page-downloads wrap"><p class="eyebrow">立即开始</p><h2>开始使用 ${escape(p.name)}</h2><p>${escape(p.platforms)} · v${escape(p.version)} · 发布于 ${escape(p.releaseDate)}</p><div>${assets}</div></section>`;
  if (isPlugin) { const overview = document.querySelector('.product-overview'); if (overview) { overview.querySelector('h2').textContent = '修改结构，也不会丢失动画。'; overview.querySelector('p:not(.eyebrow)').textContent = 'Animation Path Protector 让动画路径不再成为重构的负担。挂载到 Animator 后，节点层级、位置和名称都可以自由调整，插件会自动将动画重新接驳到正确路径。'; } const workflowTitle = document.querySelector('.workflow-section h2'); if (workflowTitle) workflowTitle.textContent = '让层级自由变化，让动画持续工作。'; const featureTitle = document.querySelector('.feature-section h2'); if (featureTitle) featureTitle.textContent = '为 Unity 动画重构而生。'; }
  const revealItems = document.querySelectorAll('.page-story'); if ('IntersectionObserver' in window) { const observer = new IntersectionObserver((entries) => entries.forEach((entry) => { if (entry.isIntersecting) { entry.target.classList.add('is-visible'); observer.unobserve(entry.target); } }), { threshold: .14 }); revealItems.forEach((item) => observer.observe(item)); } else revealItems.forEach((item) => item.classList.add('is-visible'));
  const lightbox = document.createElement('div'); lightbox.className='image-lightbox'; lightbox.innerHTML='<button type="button" aria-label="关闭图片">×</button><img alt="">'; document.body.appendChild(lightbox); const lightboxImage=lightbox.querySelector('img'); const closeLightbox=()=>lightbox.classList.remove('open'); document.querySelectorAll('.page-story figure').forEach((figure)=>figure.addEventListener('click',()=>{const img=figure.querySelector('img');lightboxImage.src=img.src;lightboxImage.alt=img.alt;lightbox.classList.add('open')})); lightbox.addEventListener('click',(event)=>{if(event.target===lightbox||event.target.tagName==='BUTTON')closeLightbox()}); document.addEventListener('keydown',(event)=>{if(event.key==='Escape')closeLightbox()});
})();
